import React from 'react'
import Script from 'next/script'
const about = () => {
  return (
    <div>
        {/* <script>
            {
                `alert("Welcome to About")`
            }
        </script> */}
      Im about
    </div>
  )
}

export default about
export const metadata = {
  title: "Facebook - About",
  description: "Generated by create next app",
};
