import React from 'react'

const contact = () => {
  return (
    <div>
      Contact
    </div>
  )
}

export default contact
export const metadata = {
  title: "Facebook - Contact",
  description: "Generated by create next app",
};
